import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, AudioLines, Bike, Truck, Ship, Plane, Check, ChevronRight, Compass, Expand, Map, Moon, Mouse, Pause, RotateCcw, Sun, Volume2, VolumeX, Waves, X } from 'lucide-react';
import { MissionUI } from './components/mission-ui';
import { EMPTY_STORY } from './story-world';
import { MISSIONS, type EndingChoice } from './campaign';
import { Button } from './components/ui/button';
import { HarborWorld, type WorldStatus } from './world';
import { PLACES, LAND_RECTS, ISLAND, BRIDGE, type PlaceId } from './geography.ts';
import { VEHICLES, type VehicleKind } from './simulation.ts';
const vehicleIcons = { bike: Bike, truck: Truck, boat: Ship, air: Plane };
const vehicleColors = ['text-teal-200 bg-teal-300/10 border-teal-200/20','text-amber-200 bg-amber-300/10 border-amber-200/20','text-blue-200 bg-blue-300/10 border-blue-200/20','text-fuchsia-200 bg-fuchsia-300/10 border-fuchsia-200/20'];

function MiniMap({ status, large = false }: { status: WorldStatus; large?: boolean }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas=ref.current!;const c=canvas.getContext('2d')!;const size=large?540:200;canvas.width=size*2;canvas.height=size*2;c.scale(2,2);const s=size/200;
    c.scale(s,s);
    const wide=large||status.vehicle==='boat'||status.vehicle==='air'||status.x>90||status.z < -110||status.z>85;
    const scale=wide?.26:.9;
    const point=(x:number,z:number):[number,number]=>[(wide?70:100)+x*scale,(z+(wide?275:125))*scale];
    const rect=(x:number,z:number,w:number,d:number,color:string)=>{const p=point(x,z);c.fillStyle=color;c.fillRect(p[0],p[1],w*scale,d*scale);};
    c.fillStyle='#142e43';c.fillRect(0,0,200,200);
    for(const land of LAND_RECTS)rect(land.x0,land.z0,land.x1-land.x0,land.z1-land.z0,'#2b494b');
    const islandPoint=point(ISLAND.x,ISLAND.z);c.fillStyle='#3b5951';c.beginPath();c.ellipse(...islandPoint,ISLAND.rx*scale,ISLAND.rz*scale,0,0,Math.PI*2);c.fill();
    rect(BRIDGE.x0,BRIDGE.z0,12,BRIDGE.z1-BRIDGE.z0,'#9cae9d');
    rect(-96,28,436,3,'#5d7470');rect(-55.5,30,11,59,'#5d7470');rect(40.5,30,11,59,'#5d7470');
    c.strokeStyle='#75958a';c.lineWidth=wide?.7:1.4;
    for(const x of [-70,-35,0,35,70]){c.beginPath();c.moveTo(...point(x,-105));c.lineTo(...point(x,28));c.stroke();}
    for(const z of [23,-16,-55,-94]){c.beginPath();c.moveTo(...point(-92,z));c.lineTo(...point(92,z));c.stroke();}
    for(let r=0;r<3;r++)for(let k=0;k<5;k++){rect(-65+k*35,-7-r*39,11,20,'#6c857c');rect(-51+k*35,-7-r*39,11,20,'#6c857c');}
    for(const [ax,az,bx,bz] of [[94,23,335,23],[35,-110,35,-244],[-80,-174,84,-174],[-80,-228,84,-228],[230,-104,230,280],[280,-104,280,24],[104,-30,332,-30],[104,-80,332,-80],[151,245,288,245]] as const){c.beginPath();c.moveTo(...point(ax,az));c.lineTo(...point(bx,bz));c.stroke();}
    c.fillStyle='#acc8b7';c.font=wide?'5px sans-serif':'8px sans-serif';c.textAlign='center';c.fillText('汐見神社',...point(0,-113));c.fillText(wide?'汐 凪 湾':'汐 凪 漁 港',...point(0,wide?135:62));rect(-3,-106,6,5,'#d0a688');
    for(const place of PLACES){const p=point(place.x,place.z);c.fillStyle=place.color;c.beginPath();c.arc(p[0],p[1],wide?2:2.5,0,Math.PI*2);c.fill();if(wide){c.font='5px sans-serif';c.fillText(place.name,p[0],p[1]-4);}}
    for(const vehicle of VEHICLES){c.fillStyle=vehicle.color;const p=point(...vehicle.home);c.beginPath();c.arc(p[0],p[1],2,0,Math.PI*2);c.fill();}
    if(status.campaign.enabled&&status.campaign.stage<6){const m=MISSIONS[status.campaign.stage],p=point(m.x,m.z);c.fillStyle='#ffd18a55';c.beginPath();c.arc(p[0],p[1],wide?7:9,0,Math.PI*2);c.fill();c.fillStyle='#ffd18a';c.beginPath();c.moveTo(p[0],p[1]-5);c.lineTo(p[0]+4,p[1]);c.lineTo(p[0],p[1]+5);c.lineTo(p[0]-4,p[1]);c.closePath();c.fill();}
    c.save();c.translate(...point(status.x,status.z));c.rotate(-status.heading);c.fillStyle='#bef5df';c.shadowColor='#8af5ce';c.shadowBlur=10;c.beginPath();c.moveTo(0,-6);c.lineTo(-4,5);c.lineTo(0,3);c.lineTo(4,5);c.closePath();c.fill();c.restore();
  },[status,large]);
  return <canvas ref={ref} aria-label="現在地を示す汐凪の地図" className={large?'aspect-square w-full max-w-[540px] rounded-md':'h-[160px] w-[160px] rounded-sm'} />;
}

export default function App() {
  const mount=useRef<HTMLDivElement>(null);const world=useRef<HarborWorld|null>(null);
  const [ready,setReady]=useState(false),[error,setError]=useState(''),[started,setStarted]=useState(false),[locked,setLocked]=useState(false),[map,setMap]=useState(false),[night,setNight]=useState(true),[sound,setSound]=useState(false),[help,setHelp]=useState(false),[garage,setGarage]=useState(false),[missions,setMissions]=useState(false);
  const [selectedPlace,setSelectedPlace]=useState<PlaceId>('market');
  const [status,setStatus]=useState<WorldStatus>({x:0,z:25,heading:0,location:'汐凪漁港',distance:0,vehicle:null,speed:0,altitude:0,nearby:null,notice:'',cruise:false,discovered:[],nearbyPlace:null,campaign:EMPTY_STORY});
  const audio=useRef<AudioContext|null>(null);
  useEffect(()=>{try{world.current=new HarborWorld(mount.current!,setStatus,setLocked);setReady(true);}catch(e){setError('3D描画を開始できませんでした。WebGL 2対応のブラウザで、ハードウェアアクセラレーションを有効にしてください。');console.error('3D初期化エラー',e);}return()=>{world.current?.dispose();world.current=null;};},[]);
  useEffect(()=>()=>{void audio.current?.close();},[]);
  const start=()=>{setStarted(true);setHelp(false);setMap(false);setGarage(false);setMissions(false);void world.current?.start();};
  const playExplore=()=>{world.current?.startExploring();start();};
  const playStory=()=>{world.current?.startStory();start();};
  const openMissions=()=>{world.current?.pause();setMap(false);setGarage(false);setMissions(true);};
  const confirmStory=(choice?:EndingChoice)=>{world.current?.confirmStory(choice);start();};
  const toggleMap=()=>{setMissions(false);if(!map)world.current?.pause();setGarage(false);setMap(v=>!v);};
  const openGarage=()=>{setMissions(false);world.current?.pause();setMap(false);setGarage(true);};
  const chooseVehicle=(id:VehicleKind)=>{world.current?.board(id);start();};
  const visitPlace=()=>{if(world.current?.travel(selectedPlace))start();else setError('この場所へは今移動できません。別の場所を選んでください。');};
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.repeat||status.campaign.dialogue||status.campaign.down)return;if(e.code==='KeyL'&&started&&status.campaign.enabled){e.preventDefault();world.current?.pause();setMap(false);setGarage(false);setMissions(v=>!v);}if(e.code==='KeyM'&&started){e.preventDefault();setMissions(false);if(!map)world.current?.pause();setGarage(false);setMap(v=>!v);}if(e.code==='KeyV'&&started){e.preventDefault();setMissions(false);world.current?.pause();setMap(false);setGarage(v=>!v);}if(e.code==='Escape'){setMissions(false);setHelp(false);setMap(false);setGarage(false);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[started,map,status.campaign.dialogue,status.campaign.down,status.campaign.enabled]);
  async function toggleSound(){
    if(!audio.current){try{const ctx=new AudioContext();audio.current=ctx;const buffer=ctx.createBuffer(1,ctx.sampleRate*5,ctx.sampleRate);const data=buffer.getChannelData(0);let prev=0;for(let i=0;i<data.length;i++){prev=(prev+Math.random()*.04-.02)/1.02;data[i]=prev*3;}const src=ctx.createBufferSource();src.buffer=buffer;src.loop=true;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=500;const gain=ctx.createGain();gain.gain.value=.22;src.connect(filter).connect(gain).connect(ctx.destination);const lfo=ctx.createOscillator();lfo.frequency.value=.12;const lfoGain=ctx.createGain();lfoGain.gain.value=.1;lfo.connect(lfoGain).connect(gain.gain);src.start();lfo.start();await ctx.resume();setSound(true);}catch{setSound(false);}return;}
    if(sound){await audio.current.suspend();setSound(false);}else{await audio.current.resume();setSound(true);}
  }
  const changeTime=()=>{world.current?.setNight(!night);setNight(!night);};
  const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setError('このブラウザでは全画面表示を利用できません。通常表示で散歩できます。');}};
  return <main className="relative h-dvh min-h-[540px] w-full overflow-hidden bg-[#0c252e] text-[#eef3e9]">
    <div ref={mount} className="absolute inset-0 touch-none" />
    <div className={`pointer-events-none absolute inset-0 ${started?'play-vignette':'landing-vignette'}`} />
    <header className="absolute inset-x-0 top-0 z-20 flex items-start justify-between px-6 py-6 md:px-10 md:py-8">
      <button onClick={()=>{world.current?.home();setStarted(false);setMap(false);setGarage(false);setMissions(false);}} aria-label="タイトル画面へ" className="group flex items-center gap-3 text-left">
        <span className="flex h-10 w-10 items-center justify-center rounded-full border border-[#c4dfce]/50"><Waves size={23} strokeWidth={1.3}/></span>
        <span><span className="block text-[13px] font-medium tracking-[.32em]">SHIONAGI</span><span className="mt-1 block text-[8px] tracking-[.22em] text-[#c3d0c7]/60">A COASTAL REVERIE</span></span>
      </button>
      <div className="flex items-center gap-2">
        <span className="mr-4 hidden items-center gap-2 font-mono text-[10px] tracking-[.12em] text-[#d7e3da]/70 sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[#a3e6c5]"/> WORLD ONLINE</span>
        <Button variant="ghost" size="icon" onClick={()=>void toggleSound()} aria-label={sound?'波音をオフ':'波音をオン'} title={sound?'波音をオフ':'波音をオン'}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</Button>
        <Button variant="ghost" size="icon" onClick={()=>void fullscreen()} aria-label="全画面を切り替え" title="全画面"> <Expand size={17}/></Button>
      </div>
    </header>
    {!started&&<>
      <section className="absolute left-6 top-[22%] z-10 md:left-[7%] md:top-[23%]">
        <div className="mb-5 flex items-center gap-3 text-[10px] tracking-[.25em] text-[#b7d7c9]"><span className="h-px w-8 bg-[#b7d7c9]/60"/> 瀬戸内の、その先へ。<span className="ml-1 rounded-sm border border-[#afc9bb]/30 px-1.5 py-1 font-mono text-[8px] tracking-wider">EXPLORABLE WORLD</span></div>
        <h1 className="title-jp text-[100px] leading-[1.1] tracking-[.06em] md:text-[144px]">汐凪<span className="ml-4 align-top font-sans text-xs font-normal tracking-[.15em] text-[#c2d9cc]/75 [writing-mode:vertical-rl] md:ml-5 md:mt-5">しおなぎ</span></h1>
        <p className="mt-4 font-mono text-[13px] tracking-[.62em] text-[#cfdfd3]/80 md:text-base">S H I O N A G I</p>
        <p className="mt-8 text-lg font-light tracking-[.13em] md:text-xl">帰港灯のない夜。</p>
        <p className="mt-4 text-xs leading-[2.3] tracking-[.08em] text-[#cfddd4]/65 md:text-[13px]">消えた灯りと、届かなかった荷物。<br/>配達員レンとなって、島々の夜をつなぎ直す。</p>
        <Button className="mt-8 h-14 min-w-60 justify-between px-6 text-[13px] tracking-widest" onClick={playStory} disabled={!ready}>物語をプレイ <ArrowRight size={18} strokeWidth={1.4}/></Button>
        <Button variant="ghost" size="sm" className="mt-3 block px-0 text-[11px] text-white/60" onClick={playExplore} disabled={!ready}>自由探索をはじめる →</Button><div className="mt-3 flex items-center gap-2 text-[9px] tracking-wider text-[#d0dfd4]/45"><span className="h-1 w-1 rounded-full bg-[#acd5bc]"/>{ready?'読み込み完了 · インストール不要':'港の風景を準備しています…'}</div>
      </section>
      <aside className="absolute bottom-28 right-10 hidden w-64 border-t border-[#c5dcd0]/30 pt-4 lg:block">
        <div className="flex items-center justify-between text-[9px] tracking-[.18em] text-[#d5e2d7]/55"><span>YOUR DESTINATION</span><Compass size={15}/></div>
        <div className="mt-4 flex items-end justify-between"><div><p className="text-xl tracking-[.18em]">汐凪漁港</p><p className="mt-2 font-mono text-[9px] tracking-[.12em] text-[#d5e2d7]/50">SHIONAGI FISHING PORT</p></div><span className="font-mono text-[10px] text-[#d7e8dc]/65">01 / 07</span></div>
        <div className="mt-5 flex gap-5 text-[10px] text-[#d7e8dc]/70"><span className="flex items-center gap-2"><Moon size={12}/>ネオンナイト</span><span className="flex items-center gap-2"><Waves size={13}/>凪</span><span>西暦 2089年</span></div>
      </aside>
      <footer className="absolute inset-x-6 bottom-5 z-10 flex items-end justify-between border-t border-[#bfd6c8]/15 pt-5 md:inset-x-10 md:bottom-7">
        <div className="flex flex-wrap gap-4 text-[10px] text-[#d2dfd5]/60 md:gap-8"><span className="flex items-center gap-2"><span className="keycap">W A S D</span>移動</span><span className="flex items-center gap-2"><Mouse size={13}/>視点操作</span><span className="hidden items-center gap-2 sm:flex"><span className="keycap">SHIFT</span>早歩き</span></div>
        <span className="text-right font-mono text-[8px] leading-5 tracking-[.13em] text-[#d2dfd5]/35">TPS ADVENTURE<br/>STORY UPDATE / 0.4</span>
      </footer>
    </>}
    {started&&<>
      {!status.campaign.enabled&&<div className="pointer-events-none absolute left-6 top-28 md:left-10"><p className="text-[9px] tracking-[.24em] text-[#c9ddcf]/65">SHIONAGI · 2089</p><h2 className="mt-2 text-2xl tracking-[.15em]">{status.location}</h2><p className="mt-2 text-[10px] text-[#b7cfbf]/60">{night?'20:42 / ネオンナイト':'16:10 / 西日'} <span className="mx-2">·</span> {status.vehicle?`${Math.round(status.speed)} km/h`:`${Math.floor(status.distance)} m 歩きました`}</p><p className="mt-2 text-[10px] tracking-wider text-teal-200/65">今回の散策 {status.discovered.length} / {PLACES.length} 地点</p></div>}
      {locked&&!status.campaign.enabled&&<div className="pointer-events-none absolute left-1/2 top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 rounded-full border border-teal-100/80"/>}
      <div className="absolute bottom-6 left-6 hidden md:block"><button className="overflow-hidden rounded-md border border-[#c0d9cb]/30 bg-[#0a252c]/70 p-2" onClick={toggleMap} aria-label="地図を開く"><MiniMap status={status}/><div className="flex items-center justify-between px-1 pt-2 text-[9px] text-[#c3dbcb]/75"><span>汐凪案内図</span><span className="keycap">M</span></div></button></div>
      {!locked&&<div className="absolute bottom-6 right-6 flex gap-2 rounded-md border border-white/10 bg-[#0b252c]/75 p-1.5 backdrop-blur-md"><Button variant="ghost" size="icon" onClick={openGarage} aria-label="乗り物を選ぶ" title="乗り物 V"><Bike size={18}/></Button><Button variant="ghost" size="icon" onClick={changeTime} aria-label="時間帯を切り替え" title="時間帯">{night?<Sun size={17}/>:<Moon size={17}/>}</Button><Button variant="ghost" size="icon" onClick={toggleMap} aria-label="地図" title="地図 M"><Map size={17}/></Button><Button variant="ghost" size="icon" onClick={()=>{world.current?.pause();setHelp(true);}} aria-label="操作説明" title="操作説明"><Mouse size={17}/></Button><Button variant="ghost" size="icon" onClick={()=>world.current?.pause()} aria-label="一時停止" title="一時停止 Esc"><Pause size={17}/></Button></div>}
      {!status.campaign.enabled&&<div className="pointer-events-none absolute bottom-8 left-1/2 hidden -translate-x-1/2 text-[9px] tracking-wider text-white/60 xl:block">{status.vehicle?'W / S 加減速 · A / D ハンドル · SPACE ブレーキ':'WASD 移動 · SHIFT 早歩き'} <span className="mx-2">/</span> V 乗り物 <span className="mx-2">/</span> ESC 休憩</div>}
      {locked&&<div className="absolute left-1/2 top-24 z-20 w-max max-w-[90vw] -translate-x-1/2 text-center">
        {status.vehicle?<div className="rounded-md border border-teal-100/20 bg-[#0e2034]/85 px-5 py-3 shadow-sm backdrop-blur-md"><p className="text-[9px] tracking-[.22em] text-teal-200/60">PILOT MODE</p><p className="mt-1 text-sm tracking-wider">{VEHICLES.find(v=>v.id===status.vehicle)?.name} <span className="ml-3 font-mono text-teal-200">{Math.round(status.speed)} <span className="text-[9px]">km/h</span></span></p><p className="mt-2 text-[10px] text-white/60">{status.vehicle==='air'?`高度 ${Math.round(status.altitude)} m · R 上昇 / Q 下降 · `:''}E 降りる · SPACE ブレーキ</p><div className="mt-2 flex justify-center gap-2"><Button variant="ghost" size="sm" onClick={()=>world.current?.toggleCruise()} className="h-7 text-[10px]" aria-label={status.cruise?'低速巡航を解除':'低速巡航を開始'}>{status.cruise?'巡航中 C':'低速巡航 C'}</Button><Button variant="ghost" size="sm" onClick={()=>world.current?.interact()} className="h-7 text-[10px]">降りる E</Button><Button variant="ghost" size="sm" onClick={openGarage} className="h-7 text-[10px]">乗り物を変える V</Button></div></div>:<Button variant="outline" onClick={status.nearby?()=>world.current?.interact():openGarage} className="border-teal-200/25 bg-[#0e2034]/85 text-xs backdrop-blur-md"><Bike size={16}/>{status.nearby?`${VEHICLES.find(v=>v.id===status.nearby)?.name}に乗る`:'陸・海・空の乗り物を選ぶ'}<span className="keycap">{status.nearby?'E':'V'}</span></Button>}
        {status.notice&&<p role="status" className="mt-3 max-w-sm rounded-md border border-amber-200/20 bg-[#263140]/95 px-4 py-3 text-xs leading-6 text-amber-100">{status.notice}</p>}
      </div>}
      {locked&&<div className="touch-controls absolute bottom-8 left-6 grid grid-cols-3 gap-1.5">{(status.vehicle==='air'?['KeyR','KeyW','KeyQ','KeyA','KeyS','KeyD','Space']:status.vehicle?['','KeyW','','KeyA','KeyS','KeyD','Space']:['','KeyW','','KeyA','KeyS','KeyD']).map((key,i)=>key?<Button key={key} variant="outline" size="icon" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);world.current?.setKey(key,true);}} onPointerUp={()=>world.current?.setKey(key,false)} onPointerCancel={()=>world.current?.setKey(key,false)} onLostPointerCapture={()=>world.current?.setKey(key,false)} aria-label={key}>{key==='KeyR'?'上昇':key==='KeyQ'?'下降':key==='Space'?'停止':key==='KeyW'?<ArrowUp size={18}/>:key==='KeyA'?<ArrowLeft size={18}/>:key==='KeyD'?<ArrowRight size={18}/>:<ArrowDown size={18}/>}</Button>:<span key={i}/>)}</div>}
      {!locked&&!map&&!garage&&!missions&&!status.campaign.dialogue&&!status.campaign.down&&<div className="absolute inset-0 z-30 flex items-center justify-center bg-[#06191e]/35 backdrop-blur-[3px]"><section className="w-[min(90vw,390px)] rounded-md border border-[#bfdccb]/20 bg-[#0e292f]/95 p-8 text-center shadow-xl"><Compass className="mx-auto mb-5 text-[#b8eee0]" size={28} strokeWidth={1.2}/><p className="text-[9px] tracking-[.3em] text-[#b4cdbd]/65">TAKE YOUR TIME</p><h2 className="mt-3 text-2xl tracking-[.14em]">少し、ひと休み。</h2><p className="mt-4 text-xs leading-7 text-[#bfd2c5]/70">{status.campaign.enabled?'任務ログで現在の目的を確認できます。':'気になる路地へ、足を向けてみてください。'}<br/>進行中の操作は一時停止しています。</p>{help&&<div className="mt-5 space-y-2 border-y border-white/10 py-4 text-left text-xs text-white/70"><p>WASD：移動 / マウス・ドラッグ：TPS視点</p><p>クリック / J：射撃、Q：ロック、R：装填</p><p>Space：回避 / E：任務操作 / L：任務ログ</p><p>↑ ↓：前後移動 / ← →：左右を向く</p><p>Shift：早歩き / M：地図 / Esc：休憩</p><p>V：車庫 / E：乗り降り / F：街の話を読む</p><p>乗り物：W/S 加減速、A/D 旋回、Space 停止</p><p>スカイポッド：R 上昇、Q 下降</p><p>タッチ：矢印で移動、画面をドラッグで視点</p></div>}<Button className="mt-6 w-full" onClick={start}>{status.vehicle?'運転をつづける':'散歩をつづける'}<ChevronRight size={16}/></Button><Button variant="outline" className="mt-3 w-full" onClick={openGarage}><Bike size={16}/>乗り物を選ぶ <span className="keycap">V</span></Button><div className="mt-3 flex justify-center gap-2"><Button variant="ghost" size="sm" onClick={()=>{world.current?.reset();start();}}><RotateCcw size={13}/>港に戻る</Button><Button variant="ghost" size="sm" onClick={toggleMap}><Map size={13}/>地図を見る</Button></div></section></div>}
    </>}
    {map&&<div className="absolute inset-0 z-40 flex items-center justify-center bg-[#05191f]/75 p-4 backdrop-blur-md"><section className="max-h-[92dvh] w-full max-w-4xl overflow-y-auto rounded-md border border-white/15 bg-[#0e292f] p-5 md:p-7"><div className="mb-5 flex items-start justify-between"><div><p className="text-[9px] tracking-[.25em] text-[#afcbb9]/60">SHIONAGI & THE ISLANDS / 07 PLACES</p><h2 className="mt-2 text-xl tracking-widest">潮風の、その先へ。</h2></div><Button size="icon" variant="ghost" onClick={()=>setMap(false)} aria-label="地図を閉じる"><X size={18}/></Button></div><div className="grid gap-6 md:grid-cols-2"><div><MiniMap status={status} large/><p className="mt-3 text-[10px] leading-6 text-white/50">橋は車と徒歩で渡れます。船は中央の高い部分を通航できます。<br/>水色の矢印が現在地。散策記録は今回のプレイ中に残ります。</p></div><div><div className="max-h-[280px] space-y-2 overflow-y-auto pr-1 [scrollbar-color:#456b68_#122c33] md:max-h-[300px]">{PLACES.map(place=><button key={place.id} onClick={()=>setSelectedPlace(place.id)} className={`flex w-full items-center justify-between rounded-md border px-4 py-3 text-left transition ${selectedPlace===place.id?'border-teal-200/50 bg-teal-200/10':'border-white/10 hover:bg-white/5'}`}><span><span className="block text-sm">{place.name}</span><span className="mt-1 block font-mono text-[8px] tracking-widest text-white/40">{place.tag}</span></span><span className="text-[10px] text-teal-200/70">{status.discovered.includes(place.id)?'訪問済み':`${Math.round(Math.hypot(status.x-place.x,status.z-place.z))} m`}</span></button>)}</div><p className="mt-4 min-h-12 text-xs leading-6 text-[#c7ddcd]/80">{PLACES.find(p=>p.id===selectedPlace)?.description}</p><Button className="mt-4 w-full" onClick={visitPlace}>この場所へ徒歩で移動 <ArrowRight size={15}/></Button><Button variant="ghost" className="mt-2 w-full" onClick={start}>現在地から散策をつづける</Button></div></div></section></div>}
    {started&&locked&&!status.vehicle&&!status.campaign.enabled&&status.nearbyPlace&&<Button variant="outline" className="absolute bottom-24 left-1/2 z-20 -translate-x-1/2 border-teal-200/25 bg-[#0e2034]/90 text-xs backdrop-blur-md" onClick={()=>world.current?.readPlace()}><span className="keycap">F</span>{PLACES.find(p=>p.id===status.nearbyPlace)?.name}の話を読む</Button>}
    {garage&&<div className="absolute inset-0 z-40 flex items-center justify-center bg-[#080e24]/75 p-4 backdrop-blur-md"><section className="max-h-[90dvh] w-full max-w-2xl overflow-y-auto rounded-md border border-fuchsia-100/20 bg-[#101e30]/95 p-5 shadow-xl md:p-8"><div className="mb-6 flex items-start justify-between"><div><p className="text-[9px] tracking-[.26em] text-teal-200/60">SHIONAGI MOBILITY / 04 VEHICLES</p><h2 className="mt-2 text-2xl tracking-widest">次は、何に乗ろう。</h2><p className="mt-3 text-xs leading-6 text-white/50">選ぶと、その乗り物の現在地へ移動して乗車します。</p></div><Button variant="ghost" size="icon" onClick={()=>setGarage(false)} aria-label="車庫を閉じる"><X size={18}/></Button></div><div className="grid gap-3 sm:grid-cols-2">{VEHICLES.map((vehicle,i)=>{const Icon=vehicleIcons[vehicle.id];return <button key={vehicle.id} onClick={()=>chooseVehicle(vehicle.id)} className={`group rounded-md border p-5 text-left transition hover:-translate-y-0.5 hover:bg-white/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-200 ${vehicleColors[i]}`}><div className="flex items-center justify-between"><Icon size={34} strokeWidth={1.3}/><span className="font-mono text-[9px] tracking-wider">0{i+1} / {Math.round(vehicle.maxSpeed*3.6)} km/h</span></div><p className="mt-5 text-base text-white">{vehicle.name}</p><p className="mt-1 font-mono text-[8px] tracking-[.15em] opacity-60">{vehicle.tag}</p><p className="mt-3 text-[11px] leading-6 text-white/55">{vehicle.description}</p><span className="mt-4 flex items-center justify-between text-[11px]">移動して乗る <ArrowRight size={15}/></span></button>;})}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-4"><span className="text-[10px] leading-6 text-white/45">W / S 加減速 · A / D 旋回 · SPACE 停止<br/>飛行：R 上昇 / Q 下降 · E 乗り降り</span><Button variant="ghost" size="sm" onClick={()=>{world.current?.reset();start();}}><RotateCcw size={13}/>港に戻って歩く</Button></div></section></div>}
    {started&&<MissionUI story={status.campaign} x={status.x} z={status.z} heading={status.heading} active={locked} onFoot={!status.vehicle} open={missions} onOpen={openMissions} onClose={start} onTravel={()=>{world.current?.missionTravel();start();}} onAction={()=>world.current?.missionAction()} onConfirm={confirmStory} onRetry={()=>{world.current?.retryStory();start();}} onFire={()=>world.current?.fire()} onReload={()=>world.current?.reloadWeapon()} onLock={()=>world.current?.lockEnemy()}/>}
    {sound&&<div className="pointer-events-none absolute right-10 top-24 flex items-center gap-2 text-[9px] tracking-wider text-[#b7d8c6]/65"><AudioLines size={12}/>波音 ON</div>}
    {error&&<div role="alert" className="absolute bottom-24 left-1/2 z-50 w-[min(90vw,520px)] -translate-x-1/2 rounded-md border border-amber-100/30 bg-[#283431] p-5 text-sm">{error}<Button variant="ghost" size="sm" onClick={()=>setError('')} className="ml-2"><Check size={15}/>閉じる</Button></div>}
  </main>;
}
